/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package touristyv1;

import CommonClasses.AdminUser;
import CommonClasses.location;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Acer
 */
public class AddUpdateDelete extends javax.swing.JFrame {

    /**
     * Creates new form AddUpdateDelete
     */
    public boolean isAdd = false;
    public boolean isUpdate = false; 
    public boolean isDelete = false;
    public AdminUser ad = null;
    public boolean isAdmin = false;
    public AdminUser curUser = null;
    public location loc = null;
    boolean hasFile = false;
    private String filePath = null;
    AdminPanel adpanel = null;
    
    public AddUpdateDelete(AdminUser ad, AdminUser curUser, location loc, boolean isAdd, boolean isUpdate, boolean isDelete, boolean isAdmin, AdminPanel adp) {
        initComponents();
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.ad = ad;
        this.isAdd = isAdd;
        this.isUpdate = isUpdate;
        this.isDelete = isDelete;
        this.isAdmin = isAdmin;
        this.curUser = curUser;
        this.loc = loc;
        adpanel = adp;
        

        String str = "";
        if (isAdd) {
            str += "ADD";
            jBtnExecute.setText("ADD");
        } else if (isUpdate) {
            str += "UPDATE";
            jBtnExecute.setText("UPDATE");
        } else {
            str += "DELETE";
            jBtnExecute.setText("DELETE");
        }
        
        if (isAdmin) {
            str += " ADMIN";
            jPass.setVisible(true);
            jTextArea1.setVisible(false); // The text area is inviible but the boundary remains. // solve this at once
            jLabel1.setText("Username");
            jLabel2.setText("Password");
            if (!isAdd) {
                jPass.setText(ad.pass);
                jTxtUsername.setText(ad.name);
                if (ad.profile_pic != null) {
                    jLblFilePath.setText("Image Already in Database");
                }
            }
        } else {
            jPass.setVisible(false);
            jTextArea1.setVisible(true);
            str += " LOCATION";
            jLabel1.setText("Location");
            jLabel2.setText("Description");
            if (!isAdd) {
                jTxtUsername.setText(loc.location);
                jTextArea1.setText(loc.description);
                jTxtUsername.disable();
                if (loc.img != null) {
                    jLblFilePath.setText("Image Already in Database");
                }
            }
        }
        
        jLblTitle.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jBtnExecute = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jTxtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        jLblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jBtnAddPhoto = new javax.swing.JButton();
        jLblFilePath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnExecute.setFont(new java.awt.Font("Bradley Hand ITC", 1, 24)); // NOI18N
        jBtnExecute.setText("ADD");
        jBtnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExecuteActionPerformed(evt);
            }
        });

        jBtnBack.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        jBtnBack.setText("BACK");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("UserName");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        jPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassActionPerformed(evt);
            }
        });

        jLblTitle.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitle.setText("ADD/ UPDATE/ DELETE");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Photo");

        jBtnAddPhoto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtnAddPhoto.setText("Add Photo");
        jBtnAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnAddPhoto)
                            .addComponent(jLblFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jPass))
                        .addContainerGap(62, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jBtnExecute)
                        .addGap(26, 26, 26)
                        .addComponent(jBtnBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLblTitle)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBtnAddPhoto))
                .addGap(4, 4, 4)
                .addComponent(jLblFilePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExecute)
                    .addComponent(jBtnBack))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExecuteActionPerformed
        if (isAdd) {
            add();
        } else if (isUpdate) {
            update();
        } else if (isDelete){
            delete();
        }
    }//GEN-LAST:event_jBtnExecuteActionPerformed

    private void jPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassActionPerformed

    private void jBtnAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddPhotoActionPerformed
        selectFile();
    }//GEN-LAST:event_jBtnAddPhotoActionPerformed

    public void selectFile () {
        JFileChooser chooser = new JFileChooser();
        File f = null;
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
        }
        if (f != null) {
            hasFile = true;
            jLblFilePath .setText(f.getAbsolutePath());
            filePath = f.getAbsolutePath();
        }
    }
    
    public void add () {
        if (isAdmin) {
            String name = jTxtUsername.getText();
            String pass = jPass.getText();
            if (!hasFile) {
                Database.DBAdmin.addAdmin(name, pass);
            } else {
                Database.DBAdmin.addAdmin(name, pass, filePath);
            }
            adpanel.loadAdminData();
            
        } else {
            if (hasFile) {
                String location = jTxtUsername.getText().toUpperCase();
                String description = jTextArea1.getText();
                Database.DBLocation.addLocation(location, description, filePath);
            } else {
                JOptionPane.showMessageDialog(null, "Image is Necessary to add a location");
                return;
            }
            adpanel.loadLocationData();
        }
        hasFile= false;
        this.dispose();
    }
    
    public void update () {
        if (isAdmin) {
            String name = jTxtUsername.getText();
            String pass = jPass.getText();
            int id = ad.id;

            if (!hasFile) {
                Database.DBAdmin.updateAdmin(name, pass, id);
            } else {
                Database.DBAdmin.updateAdmin(name, pass, filePath, id);
            }
            adpanel.loadAdminData();
        } else {
            if (!hasFile) {
                String location = jTxtUsername.getText().toUpperCase();
                String description = jTextArea1.getText();
                Database.DBLocation.updateLocation(location, description);
            } else {
                String location = jTxtUsername.getText().toUpperCase();
                String description = jTextArea1.getText();
                Database.DBLocation.updateLocation(location, description, filePath);
            }
            adpanel.loadLocationData();
        }
        hasFile= false;
        this.dispose();
    } 
    
    public void delete () {
        if (isAdmin) {
            int id = ad.id;
            Database.DBAdmin.deleteAdmin(id);
            adpanel.loadAdminData();
        } else {
            String l = loc.location;
            Database.DBLocation.deleteLocation(l);
            adpanel.loadLocationData();
        }
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUpdateDelete aud = new AddUpdateDelete(null, null, null, false, false, false, true, null);
                aud.setVisible(true);
//                new AddUpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAddPhoto;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnExecute;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblFilePath;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables
}
