package touristyv1;

import CommonClasses.AdminUser;
import CommonClasses.location;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Navo
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form mainAdmin
     */    
    AdminUser adUserArr[];
    location[] locArr;
    AdminUser curUser = new AdminUser(null);
    
    public AdminPanel(AdminUser ad) {
        initComponents();
        jTxtCurUserName.setText(ad.name);
        jTxtCurUserName.disable();
        Image dimg = ad.profile_pic.getScaledInstance(jLblCurUserPic.getWidth(), jLblCurUserPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        jLblCurUserPic.setIcon(imageIcon);
        curUser.name = ad.name;
        curUser.profile_pic = ad.profile_pic;
        curUser.id = ad.id;
        
        loadAdminData();
        loadLocationData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("touristy?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        adminQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Admin a");
        adminList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : adminQuery.getResultList();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_admin = new javax.swing.JTable();
        jBtnAddAdmin = new javax.swing.JButton();
        jBtnUpdateAdmin = new javax.swing.JButton();
        jLblAdminPic = new javax.swing.JLabel();
        jTxtAdminName = new javax.swing.JTextField();
        jBtnDeleteAdmin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_location = new javax.swing.JTable();
        jBtnDeleteLocation = new javax.swing.JButton();
        jBtnAddLocation = new javax.swing.JButton();
        jBtnUpdateLocation = new javax.swing.JButton();
        jTxtLocationName = new javax.swing.JTextField();
        jLblLocationPic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBtnExit = new javax.swing.JButton();
        jBtnSignOut = new javax.swing.JButton();
        jLblCurUserPic = new javax.swing.JLabel();
        jTxtCurUserName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab.setBackground(new java.awt.Color(204, 153, 255));
        tab.setForeground(new java.awt.Color(0, 0, 0));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        tab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_adminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_admin);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 233, 298));

        jBtnAddAdmin.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnAddAdmin.setForeground(new java.awt.Color(0, 0, 0));
        jBtnAddAdmin.setText("Add");
        jBtnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddAdminActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAddAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 70, -1));

        jBtnUpdateAdmin.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnUpdateAdmin.setForeground(new java.awt.Color(0, 0, 0));
        jBtnUpdateAdmin.setText("Update");
        jBtnUpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateAdminActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnUpdateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLblAdminPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLblAdminPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 130, 110));
        jPanel1.add(jTxtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 130, -1));

        jBtnDeleteAdmin.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnDeleteAdmin.setForeground(new java.awt.Color(0, 0, 0));
        jBtnDeleteAdmin.setText("Delete");
        jBtnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteAdminActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDeleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        tab.addTab("Admin", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_location.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_location.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_locationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_location);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 233, 298));

        jBtnDeleteLocation.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnDeleteLocation.setForeground(new java.awt.Color(0, 0, 0));
        jBtnDeleteLocation.setText("Delete");
        jBtnDeleteLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteLocationActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnDeleteLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jBtnAddLocation.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnAddLocation.setForeground(new java.awt.Color(0, 0, 0));
        jBtnAddLocation.setText("Add");
        jBtnAddLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddLocationActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAddLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 70, -1));

        jBtnUpdateLocation.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnUpdateLocation.setForeground(new java.awt.Color(0, 0, 0));
        jBtnUpdateLocation.setText("Update");
        jBtnUpdateLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateLocationActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnUpdateLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));
        jPanel2.add(jTxtLocationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 130, -1));

        jLblLocationPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jLblLocationPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 130, 110));

        tab.addTab("Location", jPanel2);

        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 610, 350));

        jLabel1.setFont(new java.awt.Font("Papyrus", 3, 48)); // NOI18N
        jLabel1.setText("DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 520, 60));

        jBtnExit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnExit.setForeground(new java.awt.Color(0, 0, 0));
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 80, -1));

        jBtnSignOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jBtnSignOut.setForeground(new java.awt.Color(0, 0, 0));
        jBtnSignOut.setText("Sign out");
        jBtnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignOutActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        jLblCurUserPic.setBackground(new java.awt.Color(255, 255, 255));
        jLblCurUserPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLblCurUserPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 130, 130));

        jTxtCurUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCurUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCurUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCurUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCurUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCurUserNameActionPerformed

    private void jBtnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignOutActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                
            }
        });
        this.dispose();
    }//GEN-LAST:event_jBtnSignOutActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void tabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabKeyPressed

    }//GEN-LAST:event_tabKeyPressed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        
    }//GEN-LAST:event_tabMouseClicked

    private void table_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_adminMouseClicked
//        DefaultTableModel model = (DefaultTableModel) table_admin.getModel();
        int selectedRowIndex = table_admin.getSelectedRow();
        jTxtAdminName.setText(adUserArr[selectedRowIndex].name);
        BufferedImage profile_pic = Database.DBAdmin.getAdminProfilePic(adUserArr[selectedRowIndex].id);
        Image dimg = profile_pic.getScaledInstance(jLblCurUserPic.getWidth(), jLblCurUserPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        jLblAdminPic.setIcon(imageIcon);
    }//GEN-LAST:event_table_adminMouseClicked

    private void table_locationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_locationMouseClicked
        int selectedRowIndex = table_location.getSelectedRow();
        jTxtLocationName.setText(locArr[selectedRowIndex].location);
        location profile_pic = Database.DBLocation.getLocationImage(locArr[selectedRowIndex].location);
        Image dimg = profile_pic.img.getScaledInstance(jLblCurUserPic.getWidth(), jLblCurUserPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        jLblLocationPic.setIcon(imageIcon);
    }//GEN-LAST:event_table_locationMouseClicked

    private void jBtnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddAdminActionPerformed
        AddUpdateDelete aud = new AddUpdateDelete(null, curUser, null, true, false, false, true, this);
        aud.pack();
        aud.setLocationRelativeTo(null);
        aud.setVisible(true);
        jLblAdminPic.setIcon(null);
        jTxtAdminName.setText("");
    }//GEN-LAST:event_jBtnAddAdminActionPerformed

    private void jBtnUpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateAdminActionPerformed
        int selectedRow = table_admin.getSelectedRow();
        if (selectedRow >= 0) {
            AdminUser selected = adUserArr[selectedRow];
            selected.profile_pic = Database.DBAdmin.getAdminProfilePic(adUserArr[selectedRow].id);
            AddUpdateDelete aud = new AddUpdateDelete(selected, curUser, null, false, true, false, true, this);
            aud.pack();
            aud.setLocationRelativeTo(null);
            aud.setVisible(true);
            jLblAdminPic.setIcon(null);
            jTxtAdminName.setText("");
        }
    }//GEN-LAST:event_jBtnUpdateAdminActionPerformed

    private void jBtnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteAdminActionPerformed
        int selectedRow = table_admin.getSelectedRow();
        if (selectedRow >= 0) {
            AdminUser selected = adUserArr[selectedRow];
            selected.profile_pic = Database.DBAdmin.getAdminProfilePic(adUserArr[selectedRow].id);
            AddUpdateDelete aud = new AddUpdateDelete(selected, curUser, null, false, false, true, true, this);
            aud.pack();
            aud.setLocationRelativeTo(null);
            aud.setVisible(true);
            jLblAdminPic.setIcon(null);
            jTxtAdminName.setText("");
        }
        
    }//GEN-LAST:event_jBtnDeleteAdminActionPerformed

    private void jBtnAddLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddLocationActionPerformed
        AddUpdateDelete aud = new AddUpdateDelete(null, curUser, null, true, false, false, false, this);
        aud.pack();
        aud.setLocationRelativeTo(null);
        aud.setVisible(true);
        jTxtLocationName.setText("");
        jLblLocationPic.setIcon(null);
    }//GEN-LAST:event_jBtnAddLocationActionPerformed

    private void jBtnUpdateLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateLocationActionPerformed
        int selectedRow = table_location.getSelectedRow();
        if (selectedRow >= 0) {
            location selected = locArr[selectedRow];
            selected.img = Database.DBLocation.getLocationImage(locArr[selectedRow].location).img;
            selected.description = Database.DBLocation.getLocationDescription(locArr[selectedRow].location);
            AddUpdateDelete aud = new AddUpdateDelete(null, curUser, selected, false, true, false, false, this);
            aud.pack();
            aud.setLocationRelativeTo(null);
            aud.setVisible(true);
            jTxtLocationName.setText("");
            jLblLocationPic.setIcon(null);
        }
    }//GEN-LAST:event_jBtnUpdateLocationActionPerformed

    private void jBtnDeleteLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteLocationActionPerformed
        int selectedRow = table_location.getSelectedRow();
        if (selectedRow >= 0) {
            location selected = locArr[selectedRow];
            selected.img = Database.DBLocation.getLocationImage(locArr[selectedRow].location).img;
            selected.description = Database.DBLocation.getLocationDescription(locArr[selectedRow].location);
            AddUpdateDelete aud = new AddUpdateDelete(null, curUser, selected, false, false, true, false, this);
            aud.pack();
            aud.setLocationRelativeTo(null);
            aud.setVisible(true);
            jTxtLocationName.setText("");
            jLblLocationPic.setIcon(null);
        }
    }//GEN-LAST:event_jBtnDeleteLocationActionPerformed
    
    public void loadLocationData() {
        locArr = Database.DBLocation.getLocationNames();
        DefaultTableModel model = (DefaultTableModel) table_location.getModel();
        model.setRowCount(0);
        int x = table_location.getRowCount();
        for (int i = x - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (int i = 0; i < locArr.length; i++) {
            // Convert the whole string to lowercase
            String lowercase = locArr[i].location.toLowerCase();
            // Capitalize the first letter
            String normalized = lowercase.substring(0, 1).toUpperCase() + lowercase.substring(1);
            String[] newData = {normalized};
            model.addRow(newData);
        }
    }
    
    public void loadAdminData() {
        AdminUser[] arr = Database.DBAdmin.getAdmins();
        adUserArr = arr;
        DefaultTableModel model = (DefaultTableModel) table_admin.getModel();

        // Remove all rows from the table
        while (model.getRowCount() > 0) {            
            model.removeRow(0);
        }
//        for (int i = 0; i < rowCount; i++) {
//            model.removeRow(0);
//        }

        // Load new data into the table
        System.out.println(adUserArr.length);
        for (int i = 0; i < adUserArr.length; i++) {
            //[] newData = {adUserArr[i].name};
            Vector<String> v = new Vector<>();
            v.add(adUserArr[i].name);
            model.addRow(v);
        }
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminPanel adp = new AdminPanel(null);
                adp.pack();
                adp.setLocationRelativeTo(null);
                adp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<touristyv1.Admin> adminList;
    private javax.persistence.Query adminQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jBtnAddAdmin;
    private javax.swing.JButton jBtnAddLocation;
    private javax.swing.JButton jBtnDeleteAdmin;
    private javax.swing.JButton jBtnDeleteLocation;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnSignOut;
    private javax.swing.JButton jBtnUpdateAdmin;
    private javax.swing.JButton jBtnUpdateLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAdminPic;
    private javax.swing.JLabel jLblCurUserPic;
    private javax.swing.JLabel jLblLocationPic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTxtAdminName;
    private javax.swing.JTextField jTxtCurUserName;
    private javax.swing.JTextField jTxtLocationName;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable table_admin;
    private javax.swing.JTable table_location;
    // End of variables declaration//GEN-END:variables
}
