package touristyv1;
import CommonClasses.CropImage;
import CommonClasses.locationImageSelector;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class GamePage extends javax.swing.JFrame {

    /**
     * Creates new form GamePage
     */
    String choice= "";
    String selec1 = "";
    String selec2 = "";
    BufferedImage []croppedimgs;
    BufferedImage []shuffled = new BufferedImage[9];
    public GamePage(String location) {
        choice = location;
        initComponents();
        CropImage cp = new CropImage();
        croppedimgs = cp.cropImage(location);
        int shuffledIndex[] = new int[10];
        shuffledIndex = shuffleNums();
        shuffled[0] = croppedimgs[shuffledIndex[1] - 1];
        shuffled[1] = croppedimgs[shuffledIndex[2] - 1];
        shuffled[2] = croppedimgs[shuffledIndex[3] - 1];
        shuffled[3] = croppedimgs[shuffledIndex[4] - 1];
        shuffled[4] = croppedimgs[shuffledIndex[5] - 1];
        shuffled[5] = croppedimgs[shuffledIndex[6] - 1];
        shuffled[6] = croppedimgs[shuffledIndex[7] - 1];
        shuffled[7] = croppedimgs[shuffledIndex[8] - 1];
        shuffled[8] = croppedimgs[shuffledIndex[9] - 1];

        gpSkipBtn.setVisible(false);
        // Setting the cropped images to the buttons
        displayImgs();
        
        
    }
    
    public void displayImgs() {
        jBtnPiece1.setIcon(new ImageIcon(shuffled[0]));
        jBtnPiece1.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece2.setIcon(new ImageIcon(shuffled[1]));
        jBtnPiece2.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece3.setIcon(new ImageIcon(shuffled[2]));
        jBtnPiece3.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece4.setIcon(new ImageIcon(shuffled[3]));
        jBtnPiece4.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece5.setIcon(new ImageIcon(shuffled[4]));
        jBtnPiece5.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece6.setIcon(new ImageIcon(shuffled[5]));
        jBtnPiece6.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece7.setIcon(new ImageIcon(shuffled[6]));
        jBtnPiece7.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece8.setIcon(new ImageIcon(shuffled[7]));
        jBtnPiece8.setBorder(BorderFactory.createEmptyBorder());
        jBtnPiece9.setIcon(new ImageIcon(shuffled[8]));
        jBtnPiece9.setBorder(BorderFactory.createEmptyBorder());
    }
    public int[] shuffleNums () {
        
        int []bNum = new int[10];
        int i, j, rowChecker;
        boolean flag = false;
        
        i = 1;
        do {
            Random rnd = new Random();
            rowChecker = rnd.nextInt((9) + 1);
            
            for (j = 0; j <= i; j++) {
                if (bNum[j] == rowChecker) {
                    flag = true;
                    break;
                } 
            }
            if (flag == true) {
                flag = false;
            } else {
                bNum[i] = rowChecker;
                i = i+1;
            }
        }while (i <=9);
        
        return bNum;
        
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        gpExitBtn = new javax.swing.JButton();
        gpBackBtn = new javax.swing.JButton();
        gpShowImgBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gpSkipBtn = new javax.swing.JButton();
        jBtnPiece1 = new javax.swing.JButton();
        jBtnPiece2 = new javax.swing.JButton();
        jBtnPiece3 = new javax.swing.JButton();
        jBtnPiece4 = new javax.swing.JButton();
        jBtnPiece6 = new javax.swing.JButton();
        jBtnPiece9 = new javax.swing.JButton();
        jBtnPiece7 = new javax.swing.JButton();
        jBtnPiece8 = new javax.swing.JButton();
        jBtnPiece5 = new javax.swing.JButton();
        jBtnSelection1 = new javax.swing.JButton();
        jBtnSelection3 = new javax.swing.JButton();
        jBtnSelection2 = new javax.swing.JButton();
        jBtnSelection4 = new javax.swing.JButton();
        jBtnSelection5 = new javax.swing.JButton();
        jBtnSelection6 = new javax.swing.JButton();
        jBtnSelection7 = new javax.swing.JButton();
        jBtnSelection8 = new javax.swing.JButton();
        jBtnSelection9 = new javax.swing.JButton();

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gpExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        gpExitBtn.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        gpExitBtn.setForeground(new java.awt.Color(0, 0, 0));
        gpExitBtn.setText("EXIT");
        gpExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gpExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpExitBtnActionPerformed(evt);
            }
        });

        gpBackBtn.setBackground(new java.awt.Color(255, 255, 255));
        gpBackBtn.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        gpBackBtn.setForeground(new java.awt.Color(0, 0, 0));
        gpBackBtn.setText("BACK");
        gpBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gpBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpBackBtnActionPerformed(evt);
            }
        });

        gpShowImgBtn.setBackground(new java.awt.Color(255, 255, 255));
        gpShowImgBtn.setFont(new java.awt.Font("Brush Script MT", 1, 23)); // NOI18N
        gpShowImgBtn.setForeground(new java.awt.Color(0, 0, 0));
        gpShowImgBtn.setText("SHOW");
        gpShowImgBtn.setToolTipText("SHOW ORIGINAL IMAGE\n");
        gpShowImgBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gpShowImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpShowImgBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Solve Puzzle To View Details Of The Site - (Click 2 images to swap)");

        gpSkipBtn.setBackground(new java.awt.Color(255, 255, 255));
        gpSkipBtn.setFont(new java.awt.Font("Brush Script MT", 1, 24)); // NOI18N
        gpSkipBtn.setForeground(new java.awt.Color(0, 0, 0));
        gpSkipBtn.setText("SKIP");
        gpSkipBtn.setFocusCycleRoot(true);
        gpSkipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpSkipBtnActionPerformed(evt);
            }
        });

        jBtnPiece1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece1ActionPerformed(evt);
            }
        });

        jBtnPiece2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece2ActionPerformed(evt);
            }
        });

        jBtnPiece3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece3ActionPerformed(evt);
            }
        });

        jBtnPiece4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece4ActionPerformed(evt);
            }
        });

        jBtnPiece6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece6ActionPerformed(evt);
            }
        });

        jBtnPiece9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece9ActionPerformed(evt);
            }
        });

        jBtnPiece7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece7ActionPerformed(evt);
            }
        });

        jBtnPiece8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece8ActionPerformed(evt);
            }
        });

        jBtnPiece5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPiece5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiece5ActionPerformed(evt);
            }
        });

        jBtnSelection1.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnSelection1.setFocusable(false);
        jBtnSelection1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection1ActionPerformed(evt);
            }
        });

        jBtnSelection3.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection3ActionPerformed(evt);
            }
        });

        jBtnSelection2.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection2ActionPerformed(evt);
            }
        });

        jBtnSelection4.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection4ActionPerformed(evt);
            }
        });

        jBtnSelection5.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection5ActionPerformed(evt);
            }
        });

        jBtnSelection6.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection6ActionPerformed(evt);
            }
        });

        jBtnSelection7.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection7ActionPerformed(evt);
            }
        });

        jBtnSelection8.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection8ActionPerformed(evt);
            }
        });

        jBtnSelection9.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSelection9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelection9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnPiece7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPiece8, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnPiece4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPiece5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnPiece6, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnPiece9, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(gpBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gpExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gpShowImgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(gpSkipBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnSelection1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSelection2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnSelection3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnSelection4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSelection5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnSelection6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnSelection7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSelection8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jBtnSelection9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpExitBtn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnPiece1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPiece2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPiece3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnPiece4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnPiece6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnPiece5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gpBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gpShowImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnSelection3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnSelection1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnSelection2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnSelection6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSelection4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSelection5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnSelection9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSelection7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSelection8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(gpSkipBtn)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnPiece8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPiece7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPiece9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gpExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpExitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_gpExitBtnActionPerformed

    private void gpBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpBackBtnActionPerformed
        LandingPage lp = new LandingPage();
        lp.pack();
        lp.setLocationRelativeTo(null);
        lp.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gpBackBtnActionPerformed

    private void gpShowImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpShowImgBtnActionPerformed
        locationImageSelector lis = new locationImageSelector();
        showPhoto sp = new showPhoto(lis.LocationImageSelector(choice));
        sp.pack();
        sp.setLocationRelativeTo(null);
        sp.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
        sp.setVisible(true);
    }//GEN-LAST:event_gpShowImgBtnActionPerformed

    private void gpSkipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpSkipBtnActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Save your Previous Note First?","Warning",JOptionPane.YES_NO_OPTION);
        if (dialogResult == 0) {
            
        }
    }//GEN-LAST:event_gpSkipBtnActionPerformed

    private void jBtnPiece1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece1ActionPerformed
        swap(1);
    }//GEN-LAST:event_jBtnPiece1ActionPerformed

    private void jBtnSelection1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection1ActionPerformed

    private void jBtnSelection3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection3ActionPerformed

    private void jBtnSelection2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtnSelection4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection4ActionPerformed

    private void jBtnSelection5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection5ActionPerformed

    private void jBtnSelection6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection6ActionPerformed

    private void jBtnSelection7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection7ActionPerformed

    private void jBtnSelection8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection8ActionPerformed

    private void jBtnSelection9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelection9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSelection9ActionPerformed

    private void jBtnPiece2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece2ActionPerformed
        swap(2);
    }//GEN-LAST:event_jBtnPiece2ActionPerformed

    private void jBtnPiece3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece3ActionPerformed
        swap(3);
    }//GEN-LAST:event_jBtnPiece3ActionPerformed

    private void jBtnPiece4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece4ActionPerformed
        swap(4);
    }//GEN-LAST:event_jBtnPiece4ActionPerformed

    private void jBtnPiece5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece5ActionPerformed
        swap(5);
    }//GEN-LAST:event_jBtnPiece5ActionPerformed

    private void jBtnPiece6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece6ActionPerformed
        swap(6);
    }//GEN-LAST:event_jBtnPiece6ActionPerformed

    private void jBtnPiece7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece7ActionPerformed
        swap(7);
    }//GEN-LAST:event_jBtnPiece7ActionPerformed

    private void jBtnPiece8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece8ActionPerformed
        swap(8);
    }//GEN-LAST:event_jBtnPiece8ActionPerformed

    private void jBtnPiece9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiece9ActionPerformed
        swap(9);
    }//GEN-LAST:event_jBtnPiece9ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GamePage gp = new GamePage("");
                gp.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
                gp.setVisible(true);
            }
        });
    }

    public void swap (int x) {
        if (selec1.equals("")) {
            selec1 = Integer.toString(x);
        } else if (selec2.equals("")) {
            selec2 = Integer.toString(x);
        }
        if (!selec1.equals("") && !selec2.equals("")) {
            checkSwap(selec1, selec2);
            selec1 = "";
            selec2 = "";
            jBtnSelection1.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection2.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection3.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection4.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection5.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection6.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection7.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection8.setBackground(new java.awt.Color(255, 255, 255));
            jBtnSelection9.setBackground(new java.awt.Color(255, 255, 255));
            isOver();
        }
        
        selected(selec1);
        selected(selec2);
    }
    
    public void checkSwap(String x, String y) {
        int num1 = Integer.parseInt(x);
        int num2 = Integer.parseInt(y);
        if ((num1 + 1) == num2) {
            switch (num1) {
                case 3:
                    if (num2 != 4) {
                        swapImg(num1, num2);
                    }   break;
                case 6:
                    if (num2 != 7) {
                        swapImg(num1, num2);
                    }   break;
                default:
                    swapImg(num1, num2);
                    break;
            }
        } else if ((num1 - 1) == num2) {
            switch (num1) {
                case 4:
                    if (num2 != 3) {
                        swapImg(num1, num2);
                    }   break;
                case 7:
                    if (num2 != 6) {
                        swapImg(num1, num2);
                    }   break;
                default:
                    swapImg(num1, num2);
                    break;
            }
        } else if ((num1 + 3) == num2) {
            swapImg(num1, num2);
        } else if ((num1 - 3) == num2) {
            swapImg(num1, num2);
        }
    }
    
    public void swapImg (int x, int y) {
        BufferedImage temp = shuffled[x-1];
        shuffled[x-1] = shuffled[y-1];
        shuffled[y-1] = temp;
        displayImgs();
    }
    
    public void selected (String x) {
        switch (x) {
            case "1":
                jBtnSelection1.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "2":
                jBtnSelection2.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "3":
                jBtnSelection3.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "4":
                jBtnSelection4.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "5":
                jBtnSelection5.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "6":
                jBtnSelection6.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "7":
                jBtnSelection7.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "8":
                jBtnSelection8.setBackground(new java.awt.Color(100, 100, 100));
                break;
            case "9":
                jBtnSelection9.setBackground(new java.awt.Color(100, 100, 100));
                break;
            default:
                break;
        }
    }
    public void isOver() {
        boolean flag = false;
        for (int x = 0; x < 9 ; x++) {
            if (shuffled[x] != croppedimgs[x]) {
                flag = true;
                break;
            }
        }
        if (!flag) {
            JOptionPane.showMessageDialog(this, "You have successfully completed the puzzle...");
            InformationPage ip = new InformationPage(choice);
            ip.pack();
            ip.setLocationRelativeTo(null);
            ip.getContentPane().setBackground(new java.awt.Color(255, 255, 255));
            ip.setVisible(true);
            this.dispose();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gpBackBtn;
    private javax.swing.JButton gpExitBtn;
    private javax.swing.JButton gpShowImgBtn;
    private javax.swing.JButton gpSkipBtn;
    private javax.swing.JButton jBtnPiece1;
    private javax.swing.JButton jBtnPiece2;
    private javax.swing.JButton jBtnPiece3;
    private javax.swing.JButton jBtnPiece4;
    private javax.swing.JButton jBtnPiece5;
    private javax.swing.JButton jBtnPiece6;
    private javax.swing.JButton jBtnPiece7;
    private javax.swing.JButton jBtnPiece8;
    private javax.swing.JButton jBtnPiece9;
    private javax.swing.JButton jBtnSelection1;
    private javax.swing.JButton jBtnSelection2;
    private javax.swing.JButton jBtnSelection3;
    private javax.swing.JButton jBtnSelection4;
    private javax.swing.JButton jBtnSelection5;
    private javax.swing.JButton jBtnSelection6;
    private javax.swing.JButton jBtnSelection7;
    private javax.swing.JButton jBtnSelection8;
    private javax.swing.JButton jBtnSelection9;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
